import random
nice = (
  "Hey there sexy!",
  "I hope your day is as nice as your face!",
  "Have you been working out?",
  "I'm lucky to be your mirror!",
  "The Force is strong with you",
  "If I could high five you... I would!",
  "On a scale from 1 to 10, you're an 15!",
  "Being awesome is hard, but you'll manage",
  "I could just hang here all day!",
  "I need some time to reflect...",
  "I see a lot of myself in you",
  "Damn. You're looking good!",
  "Yes, you are the fairest of them all",
  "May the Force be with you",
  "There's no place like home",
  "There is no spoon...",
  "Welcome to the desert of the real",
  "If you focus on what you’ve left behind, you will never be able to see what lies ahead",
  "I carried a watermelon",
  "You gotta hold the frame",
  "Never underestimate the power of denial",
  "Strangers all wanna sit next to you on the bus",
  "Coworkers fantasizes about getting stuck in the elevator with you",
  "At least two friends are going to name their child and/or goldfish after you",
  "You are freakishly good at thumb wars",
  "The FBI tapped your phone just to hear the sound of your voice",
  "You never forget to fill the ice-cube tray",
  "People enjoy you accidentally touching their butt while putting on your seat-belt",
  "I’d give you the last piece of my gum even if I’d just ate garlic",
  "You could make up a weird religion or diet and everyone would follow it",
  "Your principal would call you to the office just to look cool",
  "Your handshake conveys intelligence, confidence and minor claminess",
  "Cops admire your ability to stay a perfect 3-5 miles above the speed limit",
  "You rarely have to go to the bathroom when you fly in the window seat",
  "Cockroaches, mice and other pests avoid your place out of respect",
  "Callers are intimidated by how funny your voicemail greeting is",
  "Kids think you are the “cool old person”",
  "People always think your jeggings are regular jeans",
  "80% of motorcycle gangs think you’d be a delightful sidecar",
  "Everyone at the laundromat thinks you have the cutest underwear",
  "People behind you at movies think you are the perfect height",
  "Your parents argue over which one of them you look like",
  "Your smile is contagious",
  "You look great today",
  "You're a smart cookie",
  "I bet you make babies smile",
  "You have impeccable manners",
  "I like your style",
  "You have the best laugh",
  "I appreciate you",
  "You are the most perfect you there is",
  "Your perspective is refreshing",
  "You're an awesome friend",
  "You light up the room",
  "You deserve a hug right now",
  "You should be proud of yourself",
  "You're more helpful than you realize",
  "You have a great sense of humor",
  "You've got all the right moves!",
  "You're all that and a super-size bag of chips",
  "You're even more beautiful on the inside than you are on the outside",
  "If cartoon bluebirds were real, a bunch of them would be sitting on your shoulders singing right now",
  "You are making a difference",
  "You're like sunshine on a rainy day",
  "You bring out the best in other people",
  "Your ability to recall random factoids at just the right time is impressive",
  "You're a great listener",
  "How is it that you always look great, even in sweatpants?",
  "Everything would be better if more people were like you!",
  "I bet you sweat glitter",
  "You were cool way before hipsters were cool",
  "That color is perfect on you",
  "Hanging out with you is always a blast",
  "You smell really good",
  "Being around you makes everything better!",
  "When you say, \"I meant to do that,\" I totally believe you",
  "Colors seem brighter when you're around",
  "You're wonderful",
  "You have cute elbows. For reals!",
  "Jokes are funnier when you tell them",
  "You're better than a triple-scoop ice cream cone. With sprinkles",
  "Your bellybutton is kind of adorable",
  "Your hair looks stunning",
  "You're one of a kind!",
  "You're inspiring",
  "You should be thanked more often. So thank you!!",
  "You have the best ideas",
  "You always know how to find that silver lining",
  "Everyone gets knocked down sometimes, but you always get back up and keep going",
  "You're a candle in the darkness",
  "You're a great example to others",
  "Being around you is like being on a happy little vacation",
  "You always know just what to say",
  "You're always learning new things and trying to better yourself, which is awesome",
  "If someone based an Internet meme on you, it would have impeccable grammar",
  "You could survive a Zombie apocalypse",
  "You're more fun than bubble wrap",
  "When you make a mistake, you fix it",
  "Who raised you? They deserve a medal for a job well done",
  "You're great at figuring stuff out",
  "Your voice is magnificent",
  "The people you love are lucky to have you in their lives",
  "You're like a breath of fresh air",
  "You're gorgeous -- and that's the least interesting thing about you, too",
  "You're so thoughtful",
  "Your creative potential seems limitless",
  "Your name suits you to a T",
  "You're irresistible when you blush",
  "Actions speak louder than words, and yours tell an incredible story",
  "Somehow you make time stop and fly at the same time",
  "When you make up your mind about something, nothing stands in your way",
  "You seem to really know who you are",
  "Any team would be lucky to have you on it",
  "In high school I bet you were voted \"most likely to keep being awesome.\"",
  "Babies and small animals probably love you",
  "You're someone's reason to smile",
  "You're even better than a unicorn, because you're real",
  "How do you keep being so funny and making everyone laugh?",
  "You have a good head on your shoulders",
  "Has anyone ever told you that you have great posture?",
  "The way you treasure your loved ones is incredible",
  "You're really something special",
  "You're a gift to those around you",
  "You're so smart! Why haven't I thought of that before?",
  "You look great in that outfit",
  "You look younger than your age",
  "I like the way you smile",
  "You're so funny!",
  "Thank you for being so thoughtful",
  "Did you lose some weight? You look healthy",
  "I like you because you are a great listener",
  "You inspired me to become a better person",
  "I couldn't have finished this project without your help",
  "I like your sense of style",
  "Your hair looks amazing",
  "You smell good today",
  "You rock that shirt!",
  "Good job!",
  "I like your shoes",
  "I like the way you designed my website",
  "You have a lovely voice",
  "Your sweater looks nice. Where did you buy that?",
  "You cracked me up with that joke",
  "I love all of the photos you've taken",
  "You are a great husband",
  "That's so awesome!",
  "Have been working out lately?",
  "How do you style your hair like that?",
  "I like your pants",
  "I will recommend your service to my friends",
  "You must be the life of the party",
  "You look even better without makeup",
  "You have a great taste in clothes",
  "Take a break! You deserve a vacation",
  "How do make your skin to look flawless and radiant?",
  "Nice nails!",
  "You are one of a kind",
  "You look cool in those boots",
  "Keep up the good work!",
  "You nailed it!",
  "Those shoes were a great call. ",
  "9/10 dentists agree, you are the BEST",
  "Today's outfit = Thumbs up",
  "Your hair looks great today. It also looked really good two days ago",
  "You could be an astronaut if you wanted. NASA told me so",
  "Your dental hygiene is impeccable.  ",
  "8 out of 10 co-workers agree, your desk is the cleanest. ",
  "You'd be the last one standing in a horror movie",
  "You're funny. Like, LOL style",
  "You have very smooth hair",
  "You deserve a promotion",
  "I like your style",
  "That looks nice on you",
  "You have perfect bone structure",
  "I like your socks",
  "Your smile is breath taking",
  "You make my data circuits skip a beat",
  "You are the gravy to my mashed potatoes",
  "You're cooler than Pirates and Ninjas combined",
  "I like your pants",
  "You could probably lead a rebellion",
  "Your skin is radiant",
  "You could survive a zombie apocalypse",
  "You're so rad",
  "You're more fun than a barrel of monkeys",
  "You're nicer than a day on the beach",
  "Your glass is the fullest",
  "You look so perfect",
  "You're more fun than bubble wrap",
  "You're the bee's knees",
  "You definitely know the difference between your and you're",
  "Yum!, I dig you",
  "You got the moves like Jagger",
  "I would volunteer to take your place in the Hunger Games",
  "You have such nice eyes",
  "You're awesome",
  "You're the best",
  "You're fantastic",
  "You're really flipping smart",
  "You look awesome today, seriously"  "You're as useless as the 'ueue' in 'queue'.",
  "If I had a face like yours, I'd sue my parents.",
  "Some day you'll go far... and I hope you stay there.",
  "You must have been born on a highway cos' that's where most accidents happen.",
  "If i had a dollar for every time you said something smart, I'd be broke.",
  "When you were born the doctor threw you out the window and the window threw you back.",
  "If your brain was dynamite, there wouldn’t be enough to blow your hat off.",
  "Your face makes onions cry.",
  "I thought of you today, it reminded me to take out the trash.",
  "When karma comes back to punch you in the face, I want to be there in case it needs help.",
  "I thought I had the flu, but then I realized your face makes me sick to my stomach.",
  "You're like Mondays, everyone hates you.",
  "Keep rolling your eyes, you might find a barain back there.",
  "My phone battery lasts longer than your relationships",
  "I never forget a face, but in your case I would love to make an exception...",
  "You're so ugly when you look in the mirror your reflection looks away.",
  "You're so ugly when you were born, the doctor said aww what a treasure and your mom said yeah lets bury it.",
  "Maybe you should eat make-up so you’ll be pretty on the inside too.",
  "When you were born, the doctor came out to the waiting room and said to your dad, I'm very sorry. We did everything we could. But he pulled through.",
  "It’s a shame you can’t Photoshop your personality.",
  "Whoever told you to be yourself gave you really bad advice.",
  "If you could use 100 percent of your brain's power, you'd still be incredibly stupid. 100 percent of nothing is still nothing.",
  "Go ahead, tell us everything you know. It'll only take ten seconds.",
  "It’s not Halloweeen - take your mask off.",
  "You have a face like a smoke alarm. Beat at it until it sounds off.",
  "I never saw anybody take so long to type, and with such little result.",
  "My hair straightener is hotter than you.",
  "I’d explain it to you but I left my English-to-Dumbass Dictionary at home.",
  "I don't exactly hate you, but if you were on fire and I had water, I'd drink it.",
  "I'd love to insult you, but I'm afraid I cannot perform as well as nature did.",
  "Everyone brings happiness to a room. I do when I enter, you do when you leave.",
  "The zoo called. They're wondering how you got out of your cage.",
  "I suggest you do a little soul searching. You might just find one.",
  "I’m visualizing duck tape over your mouth.",
  "You should use a glue stick instead of chapstick.",
  "I love what you have done to your hair. How'd you get it to come so far of your nostrils?",
  "I would roast you, but my mom said not to burn trash.",
  "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
  "If your family were Starwars figures, you'd be the special edition.",
  "Over watching paint dry and listening to you, I choose watching paint dry.",
  "If you uploaded a video to Youtube with your face, it would get demonetized for `Harmful or dangerous content`.",
  "Life is great, you should get one.",
  "Fake hair, fake nails, fake smile. Are you sure you weren't made in China?",
  "Your face looks like something I would draw with my non dominant hand.",
  "You're kind of like Rapunzel except instead of letting down your hair, you let down everyone in your life.",
  "I'd agree with you but then we'd both be wrong.",
  "Brains aren't everything, in fact in your case they're nothing.",
  "Why is it acceptable for you to be an idiot but not for me to point it out?",
  "Aww, it’s so cute when you try to talk about things you don’t understand.",
  "At least when I do a handstand my stomach doesn't hit me in the face.",
  "My hair straightener is hotter than you.",
  "If you’re going to be a smart ass, first you have to be smart, otherwise you’re just an ass.",
  "People like you are the reason why people like us need meds and therapy.",
  "Some people drink from the fountain of knowledge - it appears that you merely gargled.",
  "When I see your face theres not a thing I would change... Except for the direction im walking in.",
  "You sound reasonable... Time to up my medication.",
  "I bet your brain feels as good as new, seeing that you never use it.",
  "Did your parents ever ask you to run away from home?",
  "Hey, I found your nose, it’s in my business again!",
  "Is your butt jealous of the amount of crap that just came out of your mouth?",
  "Thinking isn't your strong suit, is it?",
  "Roses are red, violets are blue, god made us beautiful, but what happened to you?",
  "Are you in great physical pain, or is that your thinking expression?",
  "Your body fat is about as evenly distributed as wealth in the US economy.",
  "Where’s your off button?",
  "It may be that your whole purpose in life is simply to serve as a warning to others.",
  "You're the reason the gene pool needs a lifeguard.",
  "You are as useless as the 'ea' in 'Tea'.",
  "People miss you as much as fish misses dry land.",
  "I guess you prove that even god makes mistakes sometimes.",
  "Mirrors don't talk, and lucky for you, they don't laugh.",
  "I'd say you're funny, but looks aren't everything.",
  "I bet you wear a nose ring because no one wants to put one on your finger.",
  "I am not ignoring you. I am simply giving you time to reflect on what an idiot you are being.",
  "Are you always so stupid or is today a special occasion?",
  "I didn’t change. I grew up. You should try it sometime.",
  "You're so stupid I don't have the time or the crayons to explain this to you.",
  "If looks could kill, you’d soon find out that yours couldn’t.",
  "I heard you were born on a farm. Any more in the litter?",
  "Shrek just called, he said he will press charges on you for `Identity Theft`",
  "There are 1,013,150 words in the entire English dialect and yet there is not a single combination of them that describes my urge to hit you with a chair.",
  "Save your breath - you're going to need it to blow up your date.",
  "I’m busy right now, can I ignore you another time?",
  "Everyone is entitled to be a fool some of the time, but you abuse the privilege.",
  "You’re not pretty enough to have such an ugly personality.",
  "Your doctor called with your colonoscopy results. Good news – they found your head.",
  "I’m sorry, what language are you speaking? It sounds like bs."
  "I’m not an astronomer but I am pretty sure the earth revolves around the sun and not you.",
  "You know that no matter how much you try, you're destined to lose.",
  "You may look like an idiot and talk like an idiot, but I don’t let that fool me. You really are an idiot.",
  "I heard you received a brain transplant but it rejected your body.",
  "You're so dumb that you got hit by a parked car.",
  "Don’t be ashamed of who you are. That’s your parents’ job.",
  "I am sorry. I cannot respond to you in any way. I am just not sufficiently interested in anything you have to say.",
  "Were you born this stupid or did you take lessons?",
  "Such a little mind - it must be lonely in such a big head.",
  "You're so ugly you make blind kids cry.",
  "You're so fat the only letters of the alphabet you know are KFC.",
  "I’m an acquired taste. If you don’t like me, acquire some taste.",
  "Too bad you can’t count jumping to conclusions and running your mouth as exercise.",
  "You look like what happens when you press random on the character creation menu.",
  "You’re pretty as a picture. I guess that explains why everyone wants to hang you.",
  "There hasn’t been a mistake this bad since Olaf the hairy, King of all the Vikings, ordered 80,000 battle helmets with the horns on the inside.",
  "I'm jealous of people that don't know you!",
  "You are more disappointing than an unsalted pretzel.",
  "You know nothing and think you know everything. That points clearly to a political career.",
  "I hear when you were a child your mother wanted to hire somebody to take care of you, but everyone said they would rather jump off a hill.",
  "Sorry, I can't understand. Idiotese is not my mother tongue.",
  "The last time I saw a face like yours I fed it a banana.",
  "You shouldn't play hide and seek, no one would look for you.",
  "Calm down. Take a deep breath and then hold it for about twenty minutes.",
  "Roses are red, violets are blue. I have five fingers and the middle one is for you.",
  "I might be crazy, but crazy is better than stupid.",
  "Have you been shopping lately? They’re selling lives – you should go get yourself one.",
  "I’ll never forget the first time we met. But I’ll keep trying.",
  "Being a stupid idiot is a tough job but someone has to do it.",
  "You’re the reason this country has to put directions on shampoo.",
  "Calling you an idiot would be an insult to all stupid people.",
  "You look like a monkey who’s been put in a suit and strategically shaved.",
  "Some babies were dropped on their heads but you were clearly thrown at a wall.",
  "You're so ugly, when you got robbed, the robbers made you wear their masks.",
  "No, no. I am listening. It just takes me a moment to process so much stupid information all at once.",
  "I would burn you but burning trash is bad for the environment.",
  "You have so many gaps in your teeth it looks like your tongue is in jail.",
  "If you’re offended by my opinion, you should hear the ones I keep to myself.",
  "You're so stupid, it takes you an hour to cook minute rice.",
  "I’d smack you, but that would be animal abuse."
)

def getcompliment():
  return random.choice(nice)